name: wallpaperplugin
description: Flutter plugin to set wallpaper in android, it can be used to directly set any image or crop and set as wallpaper.
homepage: https://github.com/ganeshsp1/wallpaperplugin
version: 0.1.2

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ganeshsp.plugins.wallpaper
        pluginClass: WallpaperPluginManager
